import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import PageWithLayoutType from '../types/pageWithLayoutType';
import MainLayout from '../components/layouts/Main';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Blog Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        home
      </div>
    </div>
  )
}

(Home as PageWithLayoutType).layout = MainLayout

export default Home
